on:
  schedule:
    - cron: '0 4,16 * * *'
  push:
    branches: main

name: Scrapear Banco Central

jobs:
  render:
    name: Scrapear Banco Central
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      
      - name: Instalar libcurl
        run: sudo apt-get install libcurl4-openssl-dev -y 
      
      - name: Instalar libxml
        run: sudo apt-get install libxml2-dev -y 
  
      - name: Instalar dependencias
        run: Rscript -e 'install.packages(c("dplyr", "rvest", "polite", stringr", "tidyr", "janitor", "readxl"))'
        
      - name: Scrapear datos
        run: Rscript obtener_datos.R
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: scraping BancoCentral